# Use postgres/example user/password credentials
version: '3.1'

services:

  database:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - backend

  backend:
    image: dariaveselkova/ecatalog-backend:1.1.0
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - backend

  frontend:
    image: dariaveselkova/ecatalog-frontend:1.0.0
    env_file:
      - .env
    ports:
      - 5001:5001
    networks:
      - backend

networks:
  backend:
