# Use postgres/example user/password credentials
version: '3.1'

services:

  database:
    image: postgres
    volumes:
      - .data/postgres:/var/lib/postgresql/data
      - .data/backups:/backups
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - backend

  backend:
    image: ghcr.io/e-catalog/backend:v1.1.2
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - backend

  frontend:
    image: ghcr.io/e-catalog/frontend:v1.0.4
    env_file:
      - .env
    ports:
      - 80:5001
    networks:
      - backend

networks:
  backend:
